Merged revisions 164436 via svnmerge from file:///srv/subversion/repos/asterisk/team/group/issue8824
................
r164436 | root | 2008-12-15 14:34:56 -0600 (Mon, 15 Dec 2008) | 73 lines

Merged revisions 164415,164417,164419,164423,164428 via svnmerge from 
file:///srv/subversion/repos/asterisk/trunk

................
r164415 | murf | 2008-12-15 13:42:05 -0600 (Mon, 15 Dec 2008) | 16 lines

I was getting this warning during a compile
on a 64-bit machine running ubuntu server 8.10, 
and gcc-4.3.2:

   [CXXi] chan_vpb.ii -> chan_vpb.oo
cc1plus: warnings being treated as errors
In file included from /home/murf/asterisk/trunk/include/asterisk/utils.h:671,
                 from chan_vpb.cc:46:
/home/murf/asterisk/trunk/include/asterisk/strings.h: In function ?\226?\128?\152char* ast_str_truncate(ast_str*, ssize_t)?\226?\128?\153:
/home/murf/asterisk/trunk/include/asterisk/strings.h:479: error: comparison between signed and unsigned integer expressions
make[1]: *** [chan_vpb.oo] Error 1
make: *** [channels] Error 2

which this fix silences


................
r164417 | tilghman | 2008-12-15 13:48:02 -0600 (Mon, 15 Dec 2008) | 3 lines

Revert ast_str opacity in chan_sip for now, since something wasn't quite right
in the merge.

................
r164419 | mmichelson | 2008-12-15 13:51:24 -0600 (Mon, 15 Dec 2008) | 12 lines

Merged revisions 164416 via svnmerge from 
https://origsvn.digium.com/svn/asterisk/branches/1.4

........
r164416 | mmichelson | 2008-12-15 13:45:07 -0600 (Mon, 15 Dec 2008) | 4 lines

Add notes to autoservice and pbx doxygen regarding a potential
deadlock scenario so that it is avoided in the future


........

................
r164423 | mmichelson | 2008-12-15 13:53:29 -0600 (Mon, 15 Dec 2008) | 11 lines

Merged revisions 164422 via svnmerge from 
https://origsvn.digium.com/svn/asterisk/branches/1.4

........
r164422 | mmichelson | 2008-12-15 13:53:08 -0600 (Mon, 15 Dec 2008) | 3 lines

Add the deadlock note to ast_spawn_extension as well


........

................
r164428 | mmichelson | 2008-12-15 14:07:03 -0600 (Mon, 15 Dec 2008) | 11 lines

Add an 'i' option to app_page. This option works the same as
the 'i' options for app_dial and app_queue, in that they will ignore
any attempts by phones to forward the call.

(closes issue #13977)
Reported by: putnopvut
Patches:
      page_ignore_forwards.patch uploaded by putnopvut (license 60)
Tested by: putnopvut, acunningham


................

................